add_newline = true

scan_timeout = 12

[username]
disabled = true

[character]
success_symbol = "[â–¶](bold green)"
error_symbol = "[â–¶](bold red)"

[package]
disabled = true

[cmd_duration]
min_time = 500
format = "ğŸ•› [$duration](bold yellow)"

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"