add_newline = true
scan_timeout = 12

[character]
success_symbol = "[â–¶](bold green)"
error_symbol   = "[â–¶](bold red)"

[cmd_duration]
format = "ðŸ•› [$duration](bold yellow)"
min_time = 500

[directory.substitutions]
"Developments" = "îž™ Developments"
"Dropbox" = "îœ‡ Dropbox"
"zenn-articles" = "ó±€ˆ Articles"
"zenn-books" = "ï€­ Books"
"~" = "ï€• Home"

[package]
disabled = true

[time]
disabled = true
format = 'ðŸ•™ [\[ $time \]]($style) '
time_format = "%T"
use_12hr = true

[username]
show_always = false
style_root = "black bold"
style_user = "white bold"
